services:
  app:
    depends_on:
      - couchdb
    build: .
    image: personas
    container_name: personas
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    # env_file: .env
    environment:
      - MNEMONIC=${MNEMONIC}
